# Generated by Django 4.2.13 on 2024-11-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_submission_day_submission_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
