# Generated by Django 4.2.13 on 2024-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.FileField(upload_to='uploads/text_files/'),
        ),
    ]
